APIVersion: v1.13.0
name: venlo2020
type: php
docroot: public
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: "Europe/Berlin"
hooks:
  post-start:
    - exec: composer install
working_dir:
  web: /var/www/html
omit_containers: [dba, ddev-ssh-agent]
